# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pr:
  - master

pool:
  name: 'Azure Pipelines'

jobs:
  - job: A
    displayName: 'Build and test project'
    workspace:
      clean: all
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: restore
          projects: 'api/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          projects: 'api/*.csproj'
          testRunTitle: 'run tests'
          arguments: '--no-restore'

  - job: B
    displayName: 'Build and push image'
    dependsOn: A
    condition: and(succeeded(A), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    steps:
      - task: Docker@1
        displayName: 'Build an image'
        inputs:
          azureSubscriptionEndpoint: 'sickly - Azure'
          azureContainerRegistry: sickly.azurecr.io
          dockerFile: api/Dockerfile
          imageName: 'sickly.azurecr.io/sickly7ab5:$(Build.BuildId)'
          useDefaultContext: false
          buildContext: api

      - task: Docker@1
        displayName: 'Push an image'
        inputs:
          azureSubscriptionEndpoint: 'sickly - Azure'
          azureContainerRegistry: sickly.azurecr.io
          command: 'Push an image'
          imageName: 'sickly.azurecr.io/sickly7ab5:$(Build.BuildId)'
  
