version: 2.1
orbs:
  node: circleci/node@1.1.6
  azure-cli: cicleci/azure-cli@1.1.0
jobs:
  build-webapp:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm install

  test-webapp:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm test
  
  build-webapp-prod:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm run build

  deploy-webapp:
    working_directory: ~/sickly/webapp/build
    executor: azure-cli/default
    steps:
      - checkout:
          path: ~/sickly
      - azure-cli/install
      - run:
          command: az storage blob upload-batch -s ./ -d $AzStorageAccountContainerName --account-name $AzStorageAccountName --account-key $AzStorageAccountKey

workflows:
  version: 2
  sickly:
    jobs:
      - build-webapp
      - test-webapp:
          requires:
            - build-webapp
      - build-webapp-prod:
          requires:
            - test-webapp
          filters:
            branches:
              only: master
      - deploy-webapp:
          requires:
            - build-webapp-prod

