version: 2.1

orbs:
  node: circleci/node@1.1.6
  azure-cli: circleci/azure-cli@1.1.0
  docker: circleci/docker@1.2.1

jobs:
  build-and-test-webapp:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - persist_to_workspace:
                root: ~/sickly/webapp
                paths:
                  - node_modules

  build-webapp-prod:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/sickly/webapp
            - run: npm run build
            - persist_to_workspace:
                root: ~/sickly/webapp
                paths:
                  - build

  deploy-webapp:
    working_directory: ~/sickly/webapp
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: ~/sickly/webapp
      - azure-cli/install
      - run:
          command: az storage blob upload-batch -s build -d '$web' --account-name sicklystorageaccount --account-key $AzStorageAccountKey
  
  build-and-test-api:
    working_directory: ~/sickly/api
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout:
          path: ~/sickly
      - persist_to_workspace:
          root: ~/sickly/api
          paths:
            - ./*
      - run: dotnet test

  build-and-deploy-api-image:
    working_directory: ~/sickly/api
    executor: docker/docker
    steps:
      - attach_workspace:
          at: ~/sickly/api
      - setup_remote_docker
      - docker/check:
          docker-password: AcrPassword
          docker-username: AcrUsername
          registry: sickly.azurecr.io
      - docker/build:
          image: sicklyapi
          registry: sickly.azurecr.io
          tag: $CIRCLE_BUILD_NUM
      - docker/push:
          image: sicklyapi
          registry: sickly.azurecr.io
          tag: $CIRCLE_BUILD_NUM
          digest-path: /tmp/digest.txt
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


workflows:
  version: 2
  sickly:
    jobs:
      - build-and-test-api
      - build-and-deploy-api-image:
          requires:
            - build-and-test-api
      # - build-and-test-webapp
      # - build-webapp-prod:
      #     requires:
      #       - build-and-test-webapp
      #     filters:
      #       branches:
      #         only: master
      # - deploy-webapp:
      #     requires:
      #       - build-webapp-prod

