version: 2.1

orbs:
  node: circleci/node@1.1.6
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build-and-test-webapp:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  build-and-deploy-webapp:
    working_directory: ~/sickly/webapp
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/sickly
      - node/with-cache:
          steps:
            - run: npm run build
            - persist-to-workspace:
                root: ~/sickly/webapp
                paths:
                  - build/*

  deploy-webapp:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: /build
      - azure-cli/install
      - run:
          command: az storage blob upload-batch -s /build -d $AzStorageAccountContainerName --account-name $AzStorageAccountName --account-key $AzStorageAccountKey

workflows:
  version: 2
  sickly:
    jobs:
      - build-and-test-webapp
      - build-and-deploy-webapp:
          requires:
            - build-and-test-webapp
          filters:
            branches:
              only: master

